/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktif kategoriler */
        get: operations["categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sağlık kontrolü
         * @description Şema için. Gerçek istekleri MIDDLEWARE başındaki HealthCheckMiddleware yanıtlar.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kategorinin Top 10 listesi */
        get: operations["leaderboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Quiz oturumu aç
         * @description Kategoriden rastgele 20 soru seçer ve ilk soruyu döner. İlk sorunun sayacı 3-2-1 sayımı kadar sonra başlar (`starts_in_ms`).
         */
        post: operations["sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/answers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cevap gönder
         * @description Cevabı (süre dolduysa `choice_id: null`) değerlendirir; sonucu ve sonraki soruyu döner. Aynı soruya tekrar gönderim ilk sonucu döner.
         */
        post: operations["sessions_answers_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/current/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * O anki soru (yenileme/devam)
         * @description Süresi dolmuş sorular sunucuda 'süre doldu' olarak kapatılır; o anki soru kalan süresiyle döner. Oturum bittiyse `question` null'dur.
         */
        get: operations["sessions_current_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/result/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Biten oturumun sonucu */
        get: operations["sessions_result_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/score/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skoru isimle kaydet
         * @description Yalnızca tamamlanmış oturum için ve bir kez kaydedilebilir.
         */
        post: operations["sessions_score_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerOut: {
            is_correct: boolean;
            timed_out: boolean;
            correct_choice_id: number;
            selected_choice_id: number | null;
            points: number;
            score: number;
            correct_count: number;
            answered_count: number;
            finished: boolean;
            next_question: components["schemas"]["QuestionOut"] | null;
        };
        AnswerRequest: {
            /** @description Cevaplanan sorunun `id` değeri. */
            question_id: number;
            /** @description Seçilen şıkkın `id` değeri (1–4). Süre dolduysa `null`. */
            choice_id: number | null;
        };
        AnswerSummary: {
            index: number;
            is_correct: boolean;
            timed_out: boolean;
            points: number;
            response_ms: number;
        };
        Category: {
            slug: string;
            /** Ad */
            name: string;
            /** Açıklama */
            description?: string;
            /**
             * Ikon
             * @description Frontend'deki ikon adı (ör. code, brain).
             */
            icon?: string;
            /** Renk */
            color: string;
            /** Sıra */
            order?: number;
        };
        CategoryBrief: {
            slug: string;
            name: string;
            color: string;
        };
        ChoiceOut: {
            /** @description Bu soruya ve oturuma özel şık kimliği (1–4). */
            id: number;
            text: string;
        };
        /**
         * @description * `web` - Web
         *     * `ios` - iOS
         *     * `android` - Android
         * @enum {string}
         */
        ClientTypeEnum: "web" | "ios" | "android";
        EntryOut: {
            id: number;
            rank: number;
            player_name: string;
            score: number;
            correct_count: number;
            total_time_ms: number;
            /** Format: date-time */
            created_at: string;
        };
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            code: string;
            message: string;
            details?: unknown;
        };
        Health: {
            status: string;
        };
        LeaderboardOut: {
            category: components["schemas"]["CategoryBrief"];
            entries: components["schemas"]["EntryOut"][];
        };
        QuestionOut: {
            /** @description Sorunun oturumdaki sırası (1–20). */
            index: number;
            id: number;
            text: string;
            /** @description 1 kolay, 2 orta, 3 zor. */
            difficulty: number;
            choices: components["schemas"]["ChoiceOut"][];
            /**
             * Format: date-time
             * @description Sayacın başladığı (başlayacağı) sunucu zamanı.
             */
            served_at: string;
            /** @description Sayaç başlayana kadar beklenecek süre (3-2-1 sayımı veya geri bildirim). */
            starts_in_ms: number;
            /** @description Sayaç başladıktan sonra kalan süre. */
            remaining_ms: number;
        };
        ResultOut: {
            /** Format: uuid */
            session_id: string;
            category: components["schemas"]["CategoryBrief"];
            score: number;
            max_score: number;
            correct_count: number;
            total_questions: number;
            total_time_ms: number;
            /** Format: date-time */
            finished_at: string;
            answers: components["schemas"]["AnswerSummary"][];
            score_saved: boolean;
            player_name: string | null;
            rank: number | null;
        };
        ScoreOut: {
            entry: components["schemas"]["EntryOut"];
            rank: number;
            /** @description Kayıt Top 10 içinde mi? */
            in_top: boolean;
            leaderboard: components["schemas"]["LeaderboardOut"];
        };
        ScoreRequest: {
            /** @description 2–20 karakter. */
            player_name: string;
        };
        SessionCreateRequest: {
            /** @description Kategori slug'ı, ör. `yapay-zeka`. */
            category: string;
            /** @default web */
            client_type: components["schemas"]["ClientTypeEnum"];
        };
        SessionStartOut: {
            /** Format: uuid */
            session_id: string;
            /** @description Yalnızca bir kez döner; `X-Session-Token`. */
            session_token: string;
            category: components["schemas"]["CategoryBrief"];
            total_questions: number;
            time_limit_ms: number;
            question: components["schemas"]["QuestionOut"];
        };
        SessionStateOut: {
            /** Format: uuid */
            session_id: string;
            status: components["schemas"]["StatusEnum"];
            category: components["schemas"]["CategoryBrief"];
            total_questions: number;
            time_limit_ms: number;
            score: number;
            correct_count: number;
            answered_count: number;
            finished: boolean;
            question: components["schemas"]["QuestionOut"] | null;
            answers: components["schemas"]["AnswerSummary"][];
        };
        /**
         * @description * `in_progress` - Devam ediyor
         *     * `completed` - Tamamlandı
         *     * `expired` - Süresi doldu
         * @enum {string}
         */
        StatusEnum: "in_progress" | "completed" | "expired";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    leaderboard_retrieve: {
        parameters: {
            query: {
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOut"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartOut"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessions_answers_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Oturum açılırken dönen `session_token`. */
                "X-Session-Token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerOut"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessions_current_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Oturum açılırken dönen `session_token`. */
                "X-Session-Token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateOut"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessions_result_retrieve: {
        parameters: {
            query?: never;
            header: {
                /** @description Oturum açılırken dönen `session_token`. */
                "X-Session-Token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultOut"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sessions_score_create: {
        parameters: {
            query?: never;
            header: {
                /** @description Oturum açılırken dönen `session_token`. */
                "X-Session-Token": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreOut"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
